#!/bin/bash

# colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
COLORRESET='\033[0m'

EXTENSION=$1
TITLE=$2

file_extension=()

remove_empty_spaces() {
  for i in *.${file_extension[@]};
  do FILENAME="$(echo -e "${i}" | sed 's/ /_/g')"
  mv "$i" "$FILENAME"
done
}

replace_old_file_name() {
  count=10001
  printf "${CYAN}Renaming files ... \n${COLORRESET}"
  for i in *.${file_extension[@]};
    do mv "$i" "${TITLE}-${count:1}.${file_extension[@]}"
    count=$((count+1));
  done
}

extend_old_file_name() {
  printf "${CYAN}Renaming files ... \n${COLORRESET}"
  for i in *.${file_extension[@]}
    do mv "$i" "${TITLE}-${i/.${file_extension[@]}}".${file_extension[@]}    
  done
}

play_it_safe() {
  read -p "Do you really want to overwrite all .$EXTENSION files in this directory? [Y/n] " REPLY
}

for i in $@; do
  if [[ $i == '--help' ]] || [[ $i == '-h' ]]; then
    printf "${GREEN}HELP!${COLORRESET}\n"
    exit;
  fi
done

if [[ $# -lt 2 ]]; then
  printf "${RED}Syntax error! ${COLORRESET}Try to run this script with the argument ${GREEN}--help ${COLORRESET}for more information.\n"
else
  for i in $@; do
    case $i in
    $EXTENSION) file_extension+=($EXTENSION) ;;
    esac
  done

  play_it_safe
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [[ $3 == '-e' ]]; then
      extend_old_file_name
    else 
      remove_empty_spaces 
      replace_old_file_name 
    fi
  else printf "${CYAN}The process was canceled. No file is renamed.${COLORRESET}\n"
  fi

fi